export const SEARCH = 'SEARCH';
export const FETCH_SEARCH_START = 'FETCH_SEARCH_START';
export const FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS';
export const FETCH_SEARCH = 'FETCH_SEARCH';
export const FETCH_SEARCH_FAIL = 'FETCH_SEARCH_FAIL';

export const FETCH_ALL_BOOKS_START = 'FETCH_ALL_BOOKS_START';
export const FETCH_ALL_BOOKS_SUCCESS = 'FETCH_ALL_BOOKS_SUCCESS';
export const FETCH_ALL_BOOKS = 'FETCH_ALL_BOOKS';
export const FETCH_ALL_BOOKS_FAIL = 'FETCH_ALL_BOOKS_FAIL';

export const LOAD_SINGLE_BOOK_START = 'LOAD_SINGLE_BOOK_START'
export const LOAD_SINGLE_BOOK_SUCCESS = 'LOAD_SINGLE_BOOK_SUCCESS'
export const LOAD_SINGLE_BOOK_FAIL = 'LOAD_SINGLE_BOOK_FAIL'

export const LOAD_SINGLE_BOOK_GO_BACK = 'LOAD_SINGLE_BOOK_GO_BACK'

export const CHANGE_GROUP = 'CHANGE_GROUP'
